name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"

[observability]
enabled = true

[[routes]]
pattern = "mail.ssvip.asia"
custom_domain = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail"
database_id = "7e3cf55d-b5c7-47af-b459-1107914fcd7b"

[[kv_namespaces]]
binding = "kv"
id = "1c94c7ac13bf4262acd7a3b0eb794d2b"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[vars]
ai_model = "@cf/meta/llama-3.1-8b-instruct"
domain = "[""ssvip.asia""]"
admin = "icy@ssvip.asia"
jwt_secret = "lhb90311."

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"